// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gomax/v1/inference.proto

package gomaxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/aep/moxgo/pkg/proto/gomax/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InferenceServiceName is the fully-qualified name of the InferenceService service.
	InferenceServiceName = "gomax.v1.InferenceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InferenceServiceInfoProcedure is the fully-qualified name of the InferenceService's Info RPC.
	InferenceServiceInfoProcedure = "/gomax.v1.InferenceService/Info"
	// InferenceServiceListProvidersProcedure is the fully-qualified name of the InferenceService's
	// ListProviders RPC.
	InferenceServiceListProvidersProcedure = "/gomax.v1.InferenceService/ListProviders"
	// InferenceServiceListProcedure is the fully-qualified name of the InferenceService's List RPC.
	InferenceServiceListProcedure = "/gomax.v1.InferenceService/List"
	// InferenceServicePsProcedure is the fully-qualified name of the InferenceService's Ps RPC.
	InferenceServicePsProcedure = "/gomax.v1.InferenceService/Ps"
	// InferenceServicePullProcedure is the fully-qualified name of the InferenceService's Pull RPC.
	InferenceServicePullProcedure = "/gomax.v1.InferenceService/Pull"
	// InferenceServiceRunProcedure is the fully-qualified name of the InferenceService's Run RPC.
	InferenceServiceRunProcedure = "/gomax.v1.InferenceService/Run"
	// InferenceServiceRmProcedure is the fully-qualified name of the InferenceService's Rm RPC.
	InferenceServiceRmProcedure = "/gomax.v1.InferenceService/Rm"
	// InferenceServicePredictProcedure is the fully-qualified name of the InferenceService's Predict
	// RPC.
	InferenceServicePredictProcedure = "/gomax.v1.InferenceService/Predict"
	// InferenceServicePredictStreamProcedure is the fully-qualified name of the InferenceService's
	// PredictStream RPC.
	InferenceServicePredictStreamProcedure = "/gomax.v1.InferenceService/PredictStream"
)

// InferenceServiceClient is a client for the gomax.v1.InferenceService service.
type InferenceServiceClient interface {
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
	ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error)
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	Ps(context.Context, *connect.Request[v1.PsRequest]) (*connect.Response[v1.PsResponse], error)
	Pull(context.Context, *connect.Request[v1.PullRequest]) (*connect.ServerStreamForClient[v1.PullEvent], error)
	Run(context.Context, *connect.Request[v1.RunRequest]) (*connect.Response[v1.RunResponse], error)
	Rm(context.Context, *connect.Request[v1.RmRequest]) (*connect.Response[v1.RmResponse], error)
	Predict(context.Context, *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error)
	PredictStream(context.Context, *connect.Request[v1.PredictStreamRequest]) (*connect.ServerStreamForClient[v1.PredictStreamResponse], error)
}

// NewInferenceServiceClient constructs a client for the gomax.v1.InferenceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInferenceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InferenceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inferenceServiceMethods := v1.File_gomax_v1_inference_proto.Services().ByName("InferenceService").Methods()
	return &inferenceServiceClient{
		info: connect.NewClient[v1.InfoRequest, v1.InfoResponse](
			httpClient,
			baseURL+InferenceServiceInfoProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
		listProviders: connect.NewClient[v1.ListProvidersRequest, v1.ListProvidersResponse](
			httpClient,
			baseURL+InferenceServiceListProvidersProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("ListProviders")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+InferenceServiceListProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		ps: connect.NewClient[v1.PsRequest, v1.PsResponse](
			httpClient,
			baseURL+InferenceServicePsProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("Ps")),
			connect.WithClientOptions(opts...),
		),
		pull: connect.NewClient[v1.PullRequest, v1.PullEvent](
			httpClient,
			baseURL+InferenceServicePullProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("Pull")),
			connect.WithClientOptions(opts...),
		),
		run: connect.NewClient[v1.RunRequest, v1.RunResponse](
			httpClient,
			baseURL+InferenceServiceRunProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("Run")),
			connect.WithClientOptions(opts...),
		),
		rm: connect.NewClient[v1.RmRequest, v1.RmResponse](
			httpClient,
			baseURL+InferenceServiceRmProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("Rm")),
			connect.WithClientOptions(opts...),
		),
		predict: connect.NewClient[v1.PredictRequest, v1.PredictResponse](
			httpClient,
			baseURL+InferenceServicePredictProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("Predict")),
			connect.WithClientOptions(opts...),
		),
		predictStream: connect.NewClient[v1.PredictStreamRequest, v1.PredictStreamResponse](
			httpClient,
			baseURL+InferenceServicePredictStreamProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("PredictStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inferenceServiceClient implements InferenceServiceClient.
type inferenceServiceClient struct {
	info          *connect.Client[v1.InfoRequest, v1.InfoResponse]
	listProviders *connect.Client[v1.ListProvidersRequest, v1.ListProvidersResponse]
	list          *connect.Client[v1.ListRequest, v1.ListResponse]
	ps            *connect.Client[v1.PsRequest, v1.PsResponse]
	pull          *connect.Client[v1.PullRequest, v1.PullEvent]
	run           *connect.Client[v1.RunRequest, v1.RunResponse]
	rm            *connect.Client[v1.RmRequest, v1.RmResponse]
	predict       *connect.Client[v1.PredictRequest, v1.PredictResponse]
	predictStream *connect.Client[v1.PredictStreamRequest, v1.PredictStreamResponse]
}

// Info calls gomax.v1.InferenceService.Info.
func (c *inferenceServiceClient) Info(ctx context.Context, req *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return c.info.CallUnary(ctx, req)
}

// ListProviders calls gomax.v1.InferenceService.ListProviders.
func (c *inferenceServiceClient) ListProviders(ctx context.Context, req *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error) {
	return c.listProviders.CallUnary(ctx, req)
}

// List calls gomax.v1.InferenceService.List.
func (c *inferenceServiceClient) List(ctx context.Context, req *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Ps calls gomax.v1.InferenceService.Ps.
func (c *inferenceServiceClient) Ps(ctx context.Context, req *connect.Request[v1.PsRequest]) (*connect.Response[v1.PsResponse], error) {
	return c.ps.CallUnary(ctx, req)
}

// Pull calls gomax.v1.InferenceService.Pull.
func (c *inferenceServiceClient) Pull(ctx context.Context, req *connect.Request[v1.PullRequest]) (*connect.ServerStreamForClient[v1.PullEvent], error) {
	return c.pull.CallServerStream(ctx, req)
}

// Run calls gomax.v1.InferenceService.Run.
func (c *inferenceServiceClient) Run(ctx context.Context, req *connect.Request[v1.RunRequest]) (*connect.Response[v1.RunResponse], error) {
	return c.run.CallUnary(ctx, req)
}

// Rm calls gomax.v1.InferenceService.Rm.
func (c *inferenceServiceClient) Rm(ctx context.Context, req *connect.Request[v1.RmRequest]) (*connect.Response[v1.RmResponse], error) {
	return c.rm.CallUnary(ctx, req)
}

// Predict calls gomax.v1.InferenceService.Predict.
func (c *inferenceServiceClient) Predict(ctx context.Context, req *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error) {
	return c.predict.CallUnary(ctx, req)
}

// PredictStream calls gomax.v1.InferenceService.PredictStream.
func (c *inferenceServiceClient) PredictStream(ctx context.Context, req *connect.Request[v1.PredictStreamRequest]) (*connect.ServerStreamForClient[v1.PredictStreamResponse], error) {
	return c.predictStream.CallServerStream(ctx, req)
}

// InferenceServiceHandler is an implementation of the gomax.v1.InferenceService service.
type InferenceServiceHandler interface {
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
	ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error)
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	Ps(context.Context, *connect.Request[v1.PsRequest]) (*connect.Response[v1.PsResponse], error)
	Pull(context.Context, *connect.Request[v1.PullRequest], *connect.ServerStream[v1.PullEvent]) error
	Run(context.Context, *connect.Request[v1.RunRequest]) (*connect.Response[v1.RunResponse], error)
	Rm(context.Context, *connect.Request[v1.RmRequest]) (*connect.Response[v1.RmResponse], error)
	Predict(context.Context, *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error)
	PredictStream(context.Context, *connect.Request[v1.PredictStreamRequest], *connect.ServerStream[v1.PredictStreamResponse]) error
}

// NewInferenceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInferenceServiceHandler(svc InferenceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inferenceServiceMethods := v1.File_gomax_v1_inference_proto.Services().ByName("InferenceService").Methods()
	inferenceServiceInfoHandler := connect.NewUnaryHandler(
		InferenceServiceInfoProcedure,
		svc.Info,
		connect.WithSchema(inferenceServiceMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	inferenceServiceListProvidersHandler := connect.NewUnaryHandler(
		InferenceServiceListProvidersProcedure,
		svc.ListProviders,
		connect.WithSchema(inferenceServiceMethods.ByName("ListProviders")),
		connect.WithHandlerOptions(opts...),
	)
	inferenceServiceListHandler := connect.NewUnaryHandler(
		InferenceServiceListProcedure,
		svc.List,
		connect.WithSchema(inferenceServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	inferenceServicePsHandler := connect.NewUnaryHandler(
		InferenceServicePsProcedure,
		svc.Ps,
		connect.WithSchema(inferenceServiceMethods.ByName("Ps")),
		connect.WithHandlerOptions(opts...),
	)
	inferenceServicePullHandler := connect.NewServerStreamHandler(
		InferenceServicePullProcedure,
		svc.Pull,
		connect.WithSchema(inferenceServiceMethods.ByName("Pull")),
		connect.WithHandlerOptions(opts...),
	)
	inferenceServiceRunHandler := connect.NewUnaryHandler(
		InferenceServiceRunProcedure,
		svc.Run,
		connect.WithSchema(inferenceServiceMethods.ByName("Run")),
		connect.WithHandlerOptions(opts...),
	)
	inferenceServiceRmHandler := connect.NewUnaryHandler(
		InferenceServiceRmProcedure,
		svc.Rm,
		connect.WithSchema(inferenceServiceMethods.ByName("Rm")),
		connect.WithHandlerOptions(opts...),
	)
	inferenceServicePredictHandler := connect.NewUnaryHandler(
		InferenceServicePredictProcedure,
		svc.Predict,
		connect.WithSchema(inferenceServiceMethods.ByName("Predict")),
		connect.WithHandlerOptions(opts...),
	)
	inferenceServicePredictStreamHandler := connect.NewServerStreamHandler(
		InferenceServicePredictStreamProcedure,
		svc.PredictStream,
		connect.WithSchema(inferenceServiceMethods.ByName("PredictStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gomax.v1.InferenceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InferenceServiceInfoProcedure:
			inferenceServiceInfoHandler.ServeHTTP(w, r)
		case InferenceServiceListProvidersProcedure:
			inferenceServiceListProvidersHandler.ServeHTTP(w, r)
		case InferenceServiceListProcedure:
			inferenceServiceListHandler.ServeHTTP(w, r)
		case InferenceServicePsProcedure:
			inferenceServicePsHandler.ServeHTTP(w, r)
		case InferenceServicePullProcedure:
			inferenceServicePullHandler.ServeHTTP(w, r)
		case InferenceServiceRunProcedure:
			inferenceServiceRunHandler.ServeHTTP(w, r)
		case InferenceServiceRmProcedure:
			inferenceServiceRmHandler.ServeHTTP(w, r)
		case InferenceServicePredictProcedure:
			inferenceServicePredictHandler.ServeHTTP(w, r)
		case InferenceServicePredictStreamProcedure:
			inferenceServicePredictStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInferenceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInferenceServiceHandler struct{}

func (UnimplementedInferenceServiceHandler) Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gomax.v1.InferenceService.Info is not implemented"))
}

func (UnimplementedInferenceServiceHandler) ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gomax.v1.InferenceService.ListProviders is not implemented"))
}

func (UnimplementedInferenceServiceHandler) List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gomax.v1.InferenceService.List is not implemented"))
}

func (UnimplementedInferenceServiceHandler) Ps(context.Context, *connect.Request[v1.PsRequest]) (*connect.Response[v1.PsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gomax.v1.InferenceService.Ps is not implemented"))
}

func (UnimplementedInferenceServiceHandler) Pull(context.Context, *connect.Request[v1.PullRequest], *connect.ServerStream[v1.PullEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("gomax.v1.InferenceService.Pull is not implemented"))
}

func (UnimplementedInferenceServiceHandler) Run(context.Context, *connect.Request[v1.RunRequest]) (*connect.Response[v1.RunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gomax.v1.InferenceService.Run is not implemented"))
}

func (UnimplementedInferenceServiceHandler) Rm(context.Context, *connect.Request[v1.RmRequest]) (*connect.Response[v1.RmResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gomax.v1.InferenceService.Rm is not implemented"))
}

func (UnimplementedInferenceServiceHandler) Predict(context.Context, *connect.Request[v1.PredictRequest]) (*connect.Response[v1.PredictResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gomax.v1.InferenceService.Predict is not implemented"))
}

func (UnimplementedInferenceServiceHandler) PredictStream(context.Context, *connect.Request[v1.PredictStreamRequest], *connect.ServerStream[v1.PredictStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("gomax.v1.InferenceService.PredictStream is not implemented"))
}
