// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gomax/v1/inference.proto

package gomaxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_gomax_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_gomax_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_gomax_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{2}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []string               `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_gomax_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *ListProvidersResponse) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_gomax_v1_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{4}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_gomax_v1_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Labels        string                 `protobuf:"bytes,3,opt,name=labels,proto3" json:"labels,omitempty"`
	Inputs        []*ModelInput          `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_gomax_v1_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{6}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ModelInfo) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *ModelInfo) GetInputs() []*ModelInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type ModelInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInput) Reset() {
	*x = ModelInput{}
	mi := &file_gomax_v1_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInput) ProtoMessage() {}

func (x *ModelInput) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInput.ProtoReflect.Descriptor instead.
func (*ModelInput) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{7}
}

func (x *ModelInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ModelInput) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type PsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsRequest) Reset() {
	*x = PsRequest{}
	mi := &file_gomax_v1_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsRequest) ProtoMessage() {}

func (x *PsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsRequest.ProtoReflect.Descriptor instead.
func (*PsRequest) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{8}
}

type PsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*RunningModel        `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsResponse) Reset() {
	*x = PsResponse{}
	mi := &file_gomax_v1_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsResponse) ProtoMessage() {}

func (x *PsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsResponse.ProtoReflect.Descriptor instead.
func (*PsResponse) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{9}
}

func (x *PsResponse) GetModels() []*RunningModel {
	if x != nil {
		return x.Models
	}
	return nil
}

type RunningModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ep            string                 `protobuf:"bytes,2,opt,name=ep,proto3" json:"ep,omitempty"`
	Threads       int32                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningModel) Reset() {
	*x = RunningModel{}
	mi := &file_gomax_v1_inference_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningModel) ProtoMessage() {}

func (x *RunningModel) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningModel.ProtoReflect.Descriptor instead.
func (*RunningModel) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{10}
}

func (x *RunningModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunningModel) GetEp() string {
	if x != nil {
		return x.Ep
	}
	return ""
}

func (x *RunningModel) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_gomax_v1_inference_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{11}
}

func (x *PullRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type PullEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Downloaded    int64                  `protobuf:"varint,3,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullEvent) Reset() {
	*x = PullEvent{}
	mi := &file_gomax_v1_inference_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullEvent) ProtoMessage() {}

func (x *PullEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullEvent.ProtoReflect.Descriptor instead.
func (*PullEvent) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{12}
}

func (x *PullEvent) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *PullEvent) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PullEvent) GetDownloaded() int64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *PullEvent) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Ep            string                 `protobuf:"bytes,2,opt,name=ep,proto3" json:"ep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_gomax_v1_inference_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{13}
}

func (x *RunRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RunRequest) GetEp() string {
	if x != nil {
		return x.Ep
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Ep            string                 `protobuf:"bytes,2,opt,name=ep,proto3" json:"ep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_gomax_v1_inference_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{14}
}

func (x *RunResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RunResponse) GetEp() string {
	if x != nil {
		return x.Ep
	}
	return ""
}

type RmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmRequest) Reset() {
	*x = RmRequest{}
	mi := &file_gomax_v1_inference_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmRequest) ProtoMessage() {}

func (x *RmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmRequest.ProtoReflect.Descriptor instead.
func (*RmRequest) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{15}
}

func (x *RmRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type RmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmResponse) Reset() {
	*x = RmResponse{}
	mi := &file_gomax_v1_inference_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmResponse) ProtoMessage() {}

func (x *RmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmResponse.ProtoReflect.Descriptor instead.
func (*RmResponse) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{16}
}

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Inputs        []*Input               `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_gomax_v1_inference_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{17}
}

func (x *PredictRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PredictRequest) GetInputs() []*Input {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type Input struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Input_FileBytes
	//	*Input_Tensor
	Data          isInput_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_gomax_v1_inference_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{18}
}

func (x *Input) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Input) GetData() isInput_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Input) GetFileBytes() []byte {
	if x != nil {
		if x, ok := x.Data.(*Input_FileBytes); ok {
			return x.FileBytes
		}
	}
	return nil
}

func (x *Input) GetTensor() *RawTensor {
	if x != nil {
		if x, ok := x.Data.(*Input_Tensor); ok {
			return x.Tensor
		}
	}
	return nil
}

type isInput_Data interface {
	isInput_Data()
}

type Input_FileBytes struct {
	FileBytes []byte `protobuf:"bytes,2,opt,name=file_bytes,json=fileBytes,proto3,oneof"`
}

type Input_Tensor struct {
	Tensor *RawTensor `protobuf:"bytes,3,opt,name=tensor,proto3,oneof"`
}

func (*Input_FileBytes) isInput_Data() {}

func (*Input_Tensor) isInput_Data() {}

type RawTensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Shape         []int64                `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawTensor) Reset() {
	*x = RawTensor{}
	mi := &file_gomax_v1_inference_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawTensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTensor) ProtoMessage() {}

func (x *RawTensor) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTensor.ProtoReflect.Descriptor instead.
func (*RawTensor) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{19}
}

func (x *RawTensor) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RawTensor) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

type PredictResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InferenceTimeMs float64                `protobuf:"fixed64,1,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
	Outputs         []*OutputResult        `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_gomax_v1_inference_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{20}
}

func (x *PredictResponse) GetInferenceTimeMs() float64 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

func (x *PredictResponse) GetOutputs() []*OutputResult {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type OutputResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shape []int64                `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*OutputResult_Classifications
	//	*OutputResult_Detections
	//	*OutputResult_Embedding
	//	*OutputResult_Raw
	Result        isOutputResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputResult) Reset() {
	*x = OutputResult{}
	mi := &file_gomax_v1_inference_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResult) ProtoMessage() {}

func (x *OutputResult) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResult.ProtoReflect.Descriptor instead.
func (*OutputResult) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{21}
}

func (x *OutputResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutputResult) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *OutputResult) GetResult() isOutputResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *OutputResult) GetClassifications() *Classifications {
	if x != nil {
		if x, ok := x.Result.(*OutputResult_Classifications); ok {
			return x.Classifications
		}
	}
	return nil
}

func (x *OutputResult) GetDetections() *Detections {
	if x != nil {
		if x, ok := x.Result.(*OutputResult_Detections); ok {
			return x.Detections
		}
	}
	return nil
}

func (x *OutputResult) GetEmbedding() *Embedding {
	if x != nil {
		if x, ok := x.Result.(*OutputResult_Embedding); ok {
			return x.Embedding
		}
	}
	return nil
}

func (x *OutputResult) GetRaw() *RawTensor {
	if x != nil {
		if x, ok := x.Result.(*OutputResult_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isOutputResult_Result interface {
	isOutputResult_Result()
}

type OutputResult_Classifications struct {
	Classifications *Classifications `protobuf:"bytes,10,opt,name=classifications,proto3,oneof"`
}

type OutputResult_Detections struct {
	Detections *Detections `protobuf:"bytes,11,opt,name=detections,proto3,oneof"`
}

type OutputResult_Embedding struct {
	Embedding *Embedding `protobuf:"bytes,12,opt,name=embedding,proto3,oneof"`
}

type OutputResult_Raw struct {
	Raw *RawTensor `protobuf:"bytes,13,opt,name=raw,proto3,oneof"`
}

func (*OutputResult_Classifications) isOutputResult_Result() {}

func (*OutputResult_Detections) isOutputResult_Result() {}

func (*OutputResult_Embedding) isOutputResult_Result() {}

func (*OutputResult_Raw) isOutputResult_Result() {}

type Classifications struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Classification      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Classifications) Reset() {
	*x = Classifications{}
	mi := &file_gomax_v1_inference_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Classifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Classifications) ProtoMessage() {}

func (x *Classifications) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Classifications.ProtoReflect.Descriptor instead.
func (*Classifications) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{22}
}

func (x *Classifications) GetItems() []*Classification {
	if x != nil {
		return x.Items
	}
	return nil
}

type Classification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	ClassId       int32                  `protobuf:"varint,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Classification) Reset() {
	*x = Classification{}
	mi := &file_gomax_v1_inference_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Classification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Classification) ProtoMessage() {}

func (x *Classification) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Classification.ProtoReflect.Descriptor instead.
func (*Classification) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{23}
}

func (x *Classification) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Classification) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Classification) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Detections struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Detection           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detections) Reset() {
	*x = Detections{}
	mi := &file_gomax_v1_inference_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detections) ProtoMessage() {}

func (x *Detections) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detections.ProtoReflect.Descriptor instead.
func (*Detections) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{24}
}

func (x *Detections) GetItems() []*Detection {
	if x != nil {
		return x.Items
	}
	return nil
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	ClassId       int32                  `protobuf:"varint,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	X1            float32                `protobuf:"fixed32,4,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,5,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            float32                `protobuf:"fixed32,6,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            float32                `protobuf:"fixed32,7,opt,name=y2,proto3" json:"y2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_gomax_v1_inference_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{25}
}

func (x *Detection) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Detection) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Detection) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Detection) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Detection) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Shape         []int64                `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_gomax_v1_inference_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{26}
}

func (x *Embedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Embedding) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

type PredictStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Inputs        []*Input               `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictStreamRequest) Reset() {
	*x = PredictStreamRequest{}
	mi := &file_gomax_v1_inference_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictStreamRequest) ProtoMessage() {}

func (x *PredictStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictStreamRequest.ProtoReflect.Descriptor instead.
func (*PredictStreamRequest) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{27}
}

func (x *PredictStreamRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PredictStreamRequest) GetInputs() []*Input {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type PredictStreamResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WindowStartSec float64                `protobuf:"fixed64,1,opt,name=window_start_sec,json=windowStartSec,proto3" json:"window_start_sec,omitempty"`
	WindowEndSec   float64                `protobuf:"fixed64,2,opt,name=window_end_sec,json=windowEndSec,proto3" json:"window_end_sec,omitempty"`
	Outputs        []*OutputResult        `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PredictStreamResponse) Reset() {
	*x = PredictStreamResponse{}
	mi := &file_gomax_v1_inference_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictStreamResponse) ProtoMessage() {}

func (x *PredictStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gomax_v1_inference_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictStreamResponse.ProtoReflect.Descriptor instead.
func (*PredictStreamResponse) Descriptor() ([]byte, []int) {
	return file_gomax_v1_inference_proto_rawDescGZIP(), []int{28}
}

func (x *PredictStreamResponse) GetWindowStartSec() float64 {
	if x != nil {
		return x.WindowStartSec
	}
	return 0
}

func (x *PredictStreamResponse) GetWindowEndSec() float64 {
	if x != nil {
		return x.WindowEndSec
	}
	return 0
}

func (x *PredictStreamResponse) GetOutputs() []*OutputResult {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_gomax_v1_inference_proto protoreflect.FileDescriptor

const file_gomax_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\x18gomax/v1/inference.proto\x12\bgomax.v1\"\r\n" +
	"\vInfoRequest\"(\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x16\n" +
	"\x14ListProvidersRequest\"5\n" +
	"\x15ListProvidersResponse\x12\x1c\n" +
	"\tproviders\x18\x01 \x03(\tR\tproviders\"\r\n" +
	"\vListRequest\";\n" +
	"\fListResponse\x12+\n" +
	"\x06models\x18\x01 \x03(\v2\x13.gomax.v1.ModelInfoR\x06models\"y\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06labels\x18\x03 \x01(\tR\x06labels\x12,\n" +
	"\x06inputs\x18\x04 \x03(\v2\x14.gomax.v1.ModelInputR\x06inputs\"\xa9\x01\n" +
	"\n" +
	"ModelInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x128\n" +
	"\x06params\x18\x03 \x03(\v2 .gomax.v1.ModelInput.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\v\n" +
	"\tPsRequest\"<\n" +
	"\n" +
	"PsResponse\x12.\n" +
	"\x06models\x18\x01 \x03(\v2\x16.gomax.v1.RunningModelR\x06models\"L\n" +
	"\fRunningModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ep\x18\x02 \x01(\tR\x02ep\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\"#\n" +
	"\vPullRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"i\n" +
	"\tPullEvent\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1e\n" +
	"\n" +
	"downloaded\x18\x03 \x01(\x03R\n" +
	"downloaded\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\"2\n" +
	"\n" +
	"RunRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x0e\n" +
	"\x02ep\x18\x02 \x01(\tR\x02ep\"3\n" +
	"\vRunResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x0e\n" +
	"\x02ep\x18\x02 \x01(\tR\x02ep\"!\n" +
	"\tRmRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"\f\n" +
	"\n" +
	"RmResponse\"O\n" +
	"\x0ePredictRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12'\n" +
	"\x06inputs\x18\x02 \x03(\v2\x0f.gomax.v1.InputR\x06inputs\"s\n" +
	"\x05Input\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\n" +
	"file_bytes\x18\x02 \x01(\fH\x00R\tfileBytes\x12-\n" +
	"\x06tensor\x18\x03 \x01(\v2\x13.gomax.v1.RawTensorH\x00R\x06tensorB\x06\n" +
	"\x04data\"5\n" +
	"\tRawTensor\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\x03R\x05shape\"o\n" +
	"\x0fPredictResponse\x12*\n" +
	"\x11inference_time_ms\x18\x01 \x01(\x01R\x0finferenceTimeMs\x120\n" +
	"\aoutputs\x18\x02 \x03(\v2\x16.gomax.v1.OutputResultR\aoutputs\"\x9f\x02\n" +
	"\fOutputResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\x03R\x05shape\x12E\n" +
	"\x0fclassifications\x18\n" +
	" \x01(\v2\x19.gomax.v1.ClassificationsH\x00R\x0fclassifications\x126\n" +
	"\n" +
	"detections\x18\v \x01(\v2\x14.gomax.v1.DetectionsH\x00R\n" +
	"detections\x123\n" +
	"\tembedding\x18\f \x01(\v2\x13.gomax.v1.EmbeddingH\x00R\tembedding\x12'\n" +
	"\x03raw\x18\r \x01(\v2\x13.gomax.v1.RawTensorH\x00R\x03rawB\b\n" +
	"\x06result\"A\n" +
	"\x0fClassifications\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.gomax.v1.ClassificationR\x05items\"W\n" +
	"\x0eClassification\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\x05R\aclassId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"7\n" +
	"\n" +
	"Detections\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.gomax.v1.DetectionR\x05items\"\x9c\x01\n" +
	"\tDetection\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\x05R\aclassId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x0e\n" +
	"\x02x1\x18\x04 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x05 \x01(\x02R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x06 \x01(\x02R\x02x2\x12\x0e\n" +
	"\x02y2\x18\a \x01(\x02R\x02y2\"9\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\x03R\x05shape\"U\n" +
	"\x14PredictStreamRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12'\n" +
	"\x06inputs\x18\x02 \x03(\v2\x0f.gomax.v1.InputR\x06inputs\"\x99\x01\n" +
	"\x15PredictStreamResponse\x12(\n" +
	"\x10window_start_sec\x18\x01 \x01(\x01R\x0ewindowStartSec\x12$\n" +
	"\x0ewindow_end_sec\x18\x02 \x01(\x01R\fwindowEndSec\x120\n" +
	"\aoutputs\x18\x03 \x03(\v2\x16.gomax.v1.OutputResultR\aoutputs2\xb2\x04\n" +
	"\x10InferenceService\x125\n" +
	"\x04Info\x12\x15.gomax.v1.InfoRequest\x1a\x16.gomax.v1.InfoResponse\x12P\n" +
	"\rListProviders\x12\x1e.gomax.v1.ListProvidersRequest\x1a\x1f.gomax.v1.ListProvidersResponse\x125\n" +
	"\x04List\x12\x15.gomax.v1.ListRequest\x1a\x16.gomax.v1.ListResponse\x12/\n" +
	"\x02Ps\x12\x13.gomax.v1.PsRequest\x1a\x14.gomax.v1.PsResponse\x124\n" +
	"\x04Pull\x12\x15.gomax.v1.PullRequest\x1a\x13.gomax.v1.PullEvent0\x01\x122\n" +
	"\x03Run\x12\x14.gomax.v1.RunRequest\x1a\x15.gomax.v1.RunResponse\x12/\n" +
	"\x02Rm\x12\x13.gomax.v1.RmRequest\x1a\x14.gomax.v1.RmResponse\x12>\n" +
	"\aPredict\x12\x18.gomax.v1.PredictRequest\x1a\x19.gomax.v1.PredictResponse\x12R\n" +
	"\rPredictStream\x12\x1e.gomax.v1.PredictStreamRequest\x1a\x1f.gomax.v1.PredictStreamResponse0\x01B1Z/github.com/aep/moxgo/pkg/proto/gomax/v1;gomaxv1b\x06proto3"

var (
	file_gomax_v1_inference_proto_rawDescOnce sync.Once
	file_gomax_v1_inference_proto_rawDescData []byte
)

func file_gomax_v1_inference_proto_rawDescGZIP() []byte {
	file_gomax_v1_inference_proto_rawDescOnce.Do(func() {
		file_gomax_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gomax_v1_inference_proto_rawDesc), len(file_gomax_v1_inference_proto_rawDesc)))
	})
	return file_gomax_v1_inference_proto_rawDescData
}

var file_gomax_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_gomax_v1_inference_proto_goTypes = []any{
	(*InfoRequest)(nil),           // 0: gomax.v1.InfoRequest
	(*InfoResponse)(nil),          // 1: gomax.v1.InfoResponse
	(*ListProvidersRequest)(nil),  // 2: gomax.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil), // 3: gomax.v1.ListProvidersResponse
	(*ListRequest)(nil),           // 4: gomax.v1.ListRequest
	(*ListResponse)(nil),          // 5: gomax.v1.ListResponse
	(*ModelInfo)(nil),             // 6: gomax.v1.ModelInfo
	(*ModelInput)(nil),            // 7: gomax.v1.ModelInput
	(*PsRequest)(nil),             // 8: gomax.v1.PsRequest
	(*PsResponse)(nil),            // 9: gomax.v1.PsResponse
	(*RunningModel)(nil),          // 10: gomax.v1.RunningModel
	(*PullRequest)(nil),           // 11: gomax.v1.PullRequest
	(*PullEvent)(nil),             // 12: gomax.v1.PullEvent
	(*RunRequest)(nil),            // 13: gomax.v1.RunRequest
	(*RunResponse)(nil),           // 14: gomax.v1.RunResponse
	(*RmRequest)(nil),             // 15: gomax.v1.RmRequest
	(*RmResponse)(nil),            // 16: gomax.v1.RmResponse
	(*PredictRequest)(nil),        // 17: gomax.v1.PredictRequest
	(*Input)(nil),                 // 18: gomax.v1.Input
	(*RawTensor)(nil),             // 19: gomax.v1.RawTensor
	(*PredictResponse)(nil),       // 20: gomax.v1.PredictResponse
	(*OutputResult)(nil),          // 21: gomax.v1.OutputResult
	(*Classifications)(nil),       // 22: gomax.v1.Classifications
	(*Classification)(nil),        // 23: gomax.v1.Classification
	(*Detections)(nil),            // 24: gomax.v1.Detections
	(*Detection)(nil),             // 25: gomax.v1.Detection
	(*Embedding)(nil),             // 26: gomax.v1.Embedding
	(*PredictStreamRequest)(nil),  // 27: gomax.v1.PredictStreamRequest
	(*PredictStreamResponse)(nil), // 28: gomax.v1.PredictStreamResponse
	nil,                           // 29: gomax.v1.ModelInput.ParamsEntry
}
var file_gomax_v1_inference_proto_depIdxs = []int32{
	6,  // 0: gomax.v1.ListResponse.models:type_name -> gomax.v1.ModelInfo
	7,  // 1: gomax.v1.ModelInfo.inputs:type_name -> gomax.v1.ModelInput
	29, // 2: gomax.v1.ModelInput.params:type_name -> gomax.v1.ModelInput.ParamsEntry
	10, // 3: gomax.v1.PsResponse.models:type_name -> gomax.v1.RunningModel
	18, // 4: gomax.v1.PredictRequest.inputs:type_name -> gomax.v1.Input
	19, // 5: gomax.v1.Input.tensor:type_name -> gomax.v1.RawTensor
	21, // 6: gomax.v1.PredictResponse.outputs:type_name -> gomax.v1.OutputResult
	22, // 7: gomax.v1.OutputResult.classifications:type_name -> gomax.v1.Classifications
	24, // 8: gomax.v1.OutputResult.detections:type_name -> gomax.v1.Detections
	26, // 9: gomax.v1.OutputResult.embedding:type_name -> gomax.v1.Embedding
	19, // 10: gomax.v1.OutputResult.raw:type_name -> gomax.v1.RawTensor
	23, // 11: gomax.v1.Classifications.items:type_name -> gomax.v1.Classification
	25, // 12: gomax.v1.Detections.items:type_name -> gomax.v1.Detection
	18, // 13: gomax.v1.PredictStreamRequest.inputs:type_name -> gomax.v1.Input
	21, // 14: gomax.v1.PredictStreamResponse.outputs:type_name -> gomax.v1.OutputResult
	0,  // 15: gomax.v1.InferenceService.Info:input_type -> gomax.v1.InfoRequest
	2,  // 16: gomax.v1.InferenceService.ListProviders:input_type -> gomax.v1.ListProvidersRequest
	4,  // 17: gomax.v1.InferenceService.List:input_type -> gomax.v1.ListRequest
	8,  // 18: gomax.v1.InferenceService.Ps:input_type -> gomax.v1.PsRequest
	11, // 19: gomax.v1.InferenceService.Pull:input_type -> gomax.v1.PullRequest
	13, // 20: gomax.v1.InferenceService.Run:input_type -> gomax.v1.RunRequest
	15, // 21: gomax.v1.InferenceService.Rm:input_type -> gomax.v1.RmRequest
	17, // 22: gomax.v1.InferenceService.Predict:input_type -> gomax.v1.PredictRequest
	27, // 23: gomax.v1.InferenceService.PredictStream:input_type -> gomax.v1.PredictStreamRequest
	1,  // 24: gomax.v1.InferenceService.Info:output_type -> gomax.v1.InfoResponse
	3,  // 25: gomax.v1.InferenceService.ListProviders:output_type -> gomax.v1.ListProvidersResponse
	5,  // 26: gomax.v1.InferenceService.List:output_type -> gomax.v1.ListResponse
	9,  // 27: gomax.v1.InferenceService.Ps:output_type -> gomax.v1.PsResponse
	12, // 28: gomax.v1.InferenceService.Pull:output_type -> gomax.v1.PullEvent
	14, // 29: gomax.v1.InferenceService.Run:output_type -> gomax.v1.RunResponse
	16, // 30: gomax.v1.InferenceService.Rm:output_type -> gomax.v1.RmResponse
	20, // 31: gomax.v1.InferenceService.Predict:output_type -> gomax.v1.PredictResponse
	28, // 32: gomax.v1.InferenceService.PredictStream:output_type -> gomax.v1.PredictStreamResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_gomax_v1_inference_proto_init() }
func file_gomax_v1_inference_proto_init() {
	if File_gomax_v1_inference_proto != nil {
		return
	}
	file_gomax_v1_inference_proto_msgTypes[18].OneofWrappers = []any{
		(*Input_FileBytes)(nil),
		(*Input_Tensor)(nil),
	}
	file_gomax_v1_inference_proto_msgTypes[21].OneofWrappers = []any{
		(*OutputResult_Classifications)(nil),
		(*OutputResult_Detections)(nil),
		(*OutputResult_Embedding)(nil),
		(*OutputResult_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gomax_v1_inference_proto_rawDesc), len(file_gomax_v1_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gomax_v1_inference_proto_goTypes,
		DependencyIndexes: file_gomax_v1_inference_proto_depIdxs,
		MessageInfos:      file_gomax_v1_inference_proto_msgTypes,
	}.Build()
	File_gomax_v1_inference_proto = out.File
	file_gomax_v1_inference_proto_goTypes = nil
	file_gomax_v1_inference_proto_depIdxs = nil
}
