name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix develop --command make cross VERSION=${{ github.ref_name }}

      - run: cp install/install.sh install/install.ps1 build/bin/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: build/bin/*
          generate_release_notes: true
